include:
  - component: git.ligo.org/computing/gitlab/components/python/all@4
    inputs:
      code_quality_analyzer: flake8
      run_advanced_sast: true
      python_versions:
        - "3.9"
        - "3.10"
        - "3.11"

python_test:
  image: ghcr.io/prefix-dev/pixi:latest
  # use pixi to manage the python environment and dependencies
  script:
    # Add pinned Python version to pixi config
    - pixi add python=${PYTHON_VERSION} --frozen
    # Install dependencies
    - pixi install
    # Install the project
    - pixi run pip install -e .
    # List the packages
    - pixi list --fields name,version,build,kind
    # Run the tests
    - pixi run pytest
        --cov=cwinpy
        --cov-report=xml:coverage.xml
        --junit-xml=junit.xml
        --pyargs
        -ra
        cwinpy.test
