version: 2

sphinx:
  # Path to your Sphinx configuration file.
  configuration: docs/conf.py

build:
  os: "ubuntu-lts-latest"
  tools:
    python: "mambaforge-latest"
  jobs:
    install:
      - pip install .[docs]
    post_install:
      # show what is installed in the build environment
      - conda list

conda:
  environment: docs-environment.yml
